### ISSUE TITLE
Undefinierter Roll-Out Status

### ISSUE THREAD

**Issue by cknoll** [fsfw-dresden/homepage-2.0-build#1]
Das neue Buildsystem mit integriertem Blog ist (offenbar) fast fertig. Es sollte aber übersichtlich zusammengefasst werden, was noch fehlt.

- Template Anpassungen
  - [ ] Links: Mitmachen, Forken, Blog
  - [ ] CSS: Problem mit Überschriften und überlappendem Logo klären, siehe #2 

- Technische Umrüstung
  - [ ] git Hook einrichten, der das Bauen der HP nach dem Pushen auslöst

**Comment by cknoll** [comment]
@horazont: Vermutlich fehlen in der Issue-Beschreibung noch Sachen. Wäre cool, wenn Du die Nachtragen könntest. Ich würde dann einzelne Issues aufmachen und mich um das kümmern, was ich kann bzw. zeitlich schaffe.

**Comment by horazont** [comment]
Nen Screenshot vom CSS-Problem für future reference wäre nett.

Für die Links müssen wir unbedingt schauen wie lange das der Platz in unserer Menüleiste noch mitmacht. Dann sollten wir auch den stefan pingen (mache ich jetzt noch nicht um das noise bei ihm niedrig zu halten :)), der denkt immer an Sachen, die ich vergesse bei sowas.

Der Git Hook ist insofern problematisch dass ich den nicht haben will bevor der [Pelican-Patch](https://github.com/getpelican/pelican/pull/2099) durch ist – das sehe ich aber nicht so bald kommen. Das Erhöht die Komplexität deutlich, da wir eine gepatchte Pelikan-Version verwenden müssen.

Ich würde das vielleicht beim FSFW-Workshoptag angehen.

**Comment by cknoll** [comment]
Ich hätte das Blog halt gerne noch vor den CLT gestartet. Zum [Pelican Patch](https://github.com/getpelican/pelican/pull/2099) habe ich einen Kommentar geschrieben, in der Hoffnung das zu beschleunigen.

Angenommen der PR wäre drin, wie viel Aufwand wäre es, den Hook einzurichten bzw. anzupassen?

**Comment by horazont** [comment]
On Montag, 27. Februar 2017 09:34:38 CET C. Knoll wrote:
> Zum [Pelican
> Patch](https://github.com/getpelican/pelican/pull/2099) habe ich einen
> Kommentar geschrieben, in der Hoffnung das zu beschleunigen.

Ich glaub nicht dass das helfen wird. Die sind hoffnungslos überlastet, klang 
im IRC an.

> Angenommen der PR wäre drin, wie viel Aufwand wäre es, den Hook einzurichten
> bzw. anzupassen?

Frag mal @sebastianriese .

> Ich hätte das Blog halt gerne noch vor den CLT gestartet. 

Dann müssen wir wohl eine gepatchte Version fahren.

**Comment by cknoll** [comment]
Wäre es eine mögliche Alternative, ein oder zwei Blogartikel lokal mit pelican zur erzeugen und als statische Seiten in die bisherige HP einzubauen?

**Comment by horazont** [comment]
On Montag, 27. Februar 2017 09:41:45 CET C. Knoll wrote:
> Wäre es eine mögliche Alternative, ein oder zwei Blogartikel lokal mit
> pelican zur erzeugen und als statische Seiten in die bisherige HP
> einzubauen?

Halte ich für ungünstig. RSS will man nicht per hand schreiben, und das bricht 
links wenn wir irgendwann auf Pelican wechseln (außer man kümmert sich manuell 
und so weiter).

**Comment by cknoll** [comment]
OK. Dann gleich richtig. Ich guck mir mal das CSS-Problem an

**Comment by horazont** [comment]
"ups" versehentlich ausgerollt.
